#ifndef TRANSPOZICEGRAFU_LOADMATRIX_FROMINPUT_H
#define TRANSPOZICEGRAFU_LOADMATRIX_FROMINPUT_H

char** loadMatrix_FromInput(long* rowSize, long* colSize);

#endif //TRANSPOZICEGRAFU_LOADMATRIX_FROMINPUT_H
