#ifndef TRANSPOZICEGRAFU_PRINTMATRIX_INPLAINFORMAT_H
#define TRANSPOZICEGRAFU_PRINTMATRIX_INPLAINFORMAT_H

void printMatrix_InPlainFormat(char ***matrix, long rowSize, long colSize);

#endif //TRANSPOZICEGRAFU_PRINTMATRIX_INPLAINFORMAT_H
